### ISSUE TITLE
reference to libswt is static to the win-32 one

### ISSUE THREAD

**Issue by tomvanoppens** [ibm-datapower/ertool#1]
Hey

It seems that you refer to libswt-win32.so
Is there a reason that you refer to an environment specific swt library ?
On windows it works like a charm (nice tool btw) on linux it doesn't.

**Comment by dmicale** [comment]
Hey Tom,

Unfortunately I had not spent the time for testing cross-platform in the GUI.  I will however put this at the top of my list to address.  To get this working correctly I need a class loader to handle each OS/64/32 bit.  The tool should still run at the command-line despite this discrepancy (least it does on my linux boxes).

Also thanks!  It is good to hear you were able to get that running in Windows for the time being.

**Comment by dmicale** [comment]
This issue should be resolved with the new ant build.xml and swt libraries.  I tested Debian 8.3.0 32-bit and Windows 7 which both worked successfully with the new build.xml.  Unfortunately I need to fix my BIOS on the machine to test a linux 64-bit install and I can't do that quite at this time.

Change: https://github.com/ibm-datapower/ertool/commit/533e3cdba851ccc245ebe71796fd4ad011b002ba

**Comment by arnabban5** [comment]
Hi dmicale,

I am not able to run ERTool on Windows with 32 bit JVM. 

I am getting following error:

Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot load 64-bit SWT libraries on 32-bit JVM\

Can you please help
