### ISSUE TITLE
MacBook arm M1 issue 

### ISSUE THREAD

**Issue by andrejgodec** [ibm-datapower/ertool#13]
Hello, 

on Mac book - M1 arm there is issue with SWT library.
Tried on intel Mac, on both same java version, intel works, arm not

`
andrej@Andrejs-MacBook-Pro dist % java --version
java 11.0.16 2022-07-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.16+11-LTS-199)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.16+11-LTS-199, mixed mode)
`

```
andrej@Andrejs-MacBook-Pro dist % java -XstartOnFirstThread -jar ErrorReport.jar -gui
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-cocoa-4948r5 in java.library.path: [/Users/andrej/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	no swt-cocoa in java.library.path: [/Users/andrej/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	no swt in java.library.path: [/Users/andrej/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	Can't load library: /Users/andrej/.swt/lib/macosx/aarch64/libswt-cocoa-4948r5.jnilib
	Can't load library: /Users/andrej/.swt/lib/macosx/aarch64/libswt-cocoa.jnilib
	Can't load library: /Users/andrej/.swt/lib/macosx/aarch64/libswt.jnilib
	Can't load library: /Users/andrej/.swt/lib/macosx/aarch64/libswt-cocoa-4948r5.jnilib

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:348)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:257)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:107)
	at com.ibm.datapower.er.erGUI.<init>(Unknown Source)
	at com.ibm.datapower.er.ERTool.GetGUIArgs(Unknown Source)
	at com.ibm.datapower.er.ERTool.<init>(Unknown Source)
	at com.ibm.datapower.er.ERTool.main(Unknown Source)
```

**Comment by dmicale** [comment]
We had other members in IBM such as @aharbis help add support for the Mac OS -- I do not have a system to test this unfortunately.  ERTool was traditionally made for x86_64, you are trying to compile for aarch64 which it can't find the libraries.  You would need to go to the SWT site and obtain them:

	Can't load library: /Users/andrej/.swt/lib/macosx/aarch64/libswt-cocoa-4948r5.jnilib
	Can't load library: /Users/andrej/.swt/lib/macosx/aarch64/libswt-cocoa.jnilib
	Can't load library: /Users/andrej/.swt/lib/macosx/aarch64/libswt.jnilib
	Can't load library: /Users/andrej/.swt/lib/macosx/aarch64/libswt-cocoa-4948r5.jnilib

https://search.maven.org/artifact/org.eclipse.platform/org.eclipse.swt.cocoa.macosx.aarch64

**Comment by andrejgodec** [comment]
Yes I figure it out to edit _build.xml_  <include if:set="ismac" name="swt.jar"/> then as download and rename set.jar 

Mac OSX (64 bit version for Arm64/AArch64) | swt-4.25RC1-cocoa-macosx-aarch64.zip | 3.5 MB
-- | -- | --


Mac OSX (64 bit version for Arm64/AArch64)	[swt-4.25RC1-cocoa-macosx-aarch64.zip](https://download.eclipse.org/eclipse/downloads/drops4/S-4.25RC1-202208241800/download.php?dropFile=swt-4.25RC1-cocoa-macosx-aarch64.zip)	3.5 MB
