### ISSUE TITLE
Java compilation error in AnalyticsProcessor.java:365

### ISSUE THREAD

**Issue by rajdhandus** [ibm-datapower/ertool#7]
sh-3.2$ ant
Buildfile: /Users/xx/Document/GitHub/ertool/framework/build.xml

init:
    [mkdir] Created dir: /Users/xx/Document/GitHub/ertool/framework/bin
    [mkdir] Created dir: /Users/xx/Document/GitHub/ertool/framework/bin/tools

compile:
    [javac] /Users/xx/Document/GitHub/ertool/framework/build.xml:62: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 82 source files to /Users/xx/Document/GitHub/ertool/framework/bin
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] /Users/xx/Document/GitHub/ertool/framework/src/com/ibm/datapower/er/Analytics/AnalyticsProcessor.java:365: error: ')' expected
    [javac]                                             if ( ordField.getFieldValue().startsWith(("{Condition:"))
    [javac]                                                                                                      ^
    [javac] 1 error
    [javac] 1 warning

BUILD FAILED
/Users/xx/Document/GitHub/ertool/framework/build.xml:62: Compile failed; see the compiler error output for details.

**Comment by dmicale** [comment]
Terrible mistake on my part thanks for bringing this to my attention.  Did double check this time and it compiled succesfully on ANT 1.10.1 - let me know if there are further issues.
